version: "3.8"

services:
  mongo:
    image: mongo:latest
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    image: exl7954/metguessr:backend-latest
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGO_HOST=mongo

  frontend:
    image: exl7954/metguessr:frontend-latest
    ports:
      - '80:80'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  
volumes:
  mongo-data:
    driver: local