version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports: 
      - '27017:27017'
    networks:
      - app-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - app-network
    environment:
      - MONGO_HOST=mongo

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge