# pytest settings that might help... feel free to modify or remove as needed

[tool.pytest.ini_options]
minversion = "7.0" # minimum pytest version
addopts = "-ra -q" # default pytest command line options
pythonpath = [
  "."
]
testpaths = [
    "tests",
]
