name: Run Pytest on Backend

on:
  push:
    paths:
      - "backend/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  pytest-backend:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ping: 1})'"
          --health-interval 20s 
          --health-timeout 10s 
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pytest
      
      - name: Wait for MongoDB
        run: |
          while ! nc -z localhost 27017; do   
            echo Waiting for MongoDB to start...
            sleep 1
          done

      - name: Test with Pytest
        working-directory: ./backend
        run: python -m pytest
