name: Redeploy on Droplet

on:
  workflow_run:
    branches:
      - main
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Restart Docker Compose
        run: |
          ssh -o "StrictHostKeyChecking=no" root@64.225.55.188 "cd ~/5-final-project-spring-2024-ics5 && docker compose down && docker compose pull && docker compose up -d"